### ISSUE TITLE
Issue нужно закрывать сообщениями коммита

### ISSUE THREAD

**Issue by coursar** [sgv1995/wallpaperCalculator#8]

**Comment by sgv1995** [comment]
А можете напомнить как "Issue нужно закрывать сообщениями коммита" на лекции вроде говорили там через # и номер issue, а дальше не помню. Это я так понял надо написать в issue с замечанием и дальше вроде что-то с кодом надо сделать или вставить его как-то?

**Comment by sgv1995** [comment]
А вроде вспомнил, в intellij IDEA где commit and push делаем в комментарии нужно номер issue указывать через #.  В следующий раз так и буду делать.
